/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

import static ventanas.Login.user;
 //importamos el nombre del usuario logueado que es quien va a registarar este cliente y viene desde la vista capturista
import static ventanas.Capturista.nombre_usuario_logueado;
//id del cliente que viene de la var estatica de gestioanr clientes
import static ventanas.GestinarClientes.cliente_update;




/**
 *
 * @author Lenovo
 */
public class InformacionCliente extends javax.swing.JFrame {
    //usuario de variable statica de login
    String user;
    //nombre del suaurio logueado que viene de variable estatica de capturista
    String user_logueado;
    //para recibir la variable estatica del id del cliente a modificar que viene de vista gestionarclientes
    int id_clientes;

    /**
     * Creates new form InformacionCliente
     */
    public InformacionCliente() {
        initComponents();
        
          //aca recuperamos los datos de la ventana login  en los constructores es que podemos trabajar con ellos
        //aca decimos que en la user que cree yo en esta clase sea igual a la interface login .user que esta en la case login declarada asi pasamos de alla aca
        user=Login.user;
        user_logueado=Capturista.nombre_usuario_logueado;
        id_clientes=GestinarClientes.cliente_update;
       
        //TAMANP DE PANTALLA
        setSize(706, 395);
        //NO PUEDA CAMBIARLAS
        setResizable(false);
        //esto es para yo validar en el titulo a ver si si me llega el id que vamosa  editar
        String cliente_editar_Str = String.valueOf(id_clientes);
        
        //titulo de la intefaz de login
        setTitle("Panel Adminitrador sesion de -"+user+" nombre "+user_logueado+" id a editar"+cliente_editar_Str);
        //centrar la interface en la pantalla
        setLocationRelativeTo(null);
        
   
        
         //matamos proceso cuando se loguean destruimos la ejecucion de login para que solo siga esta ventana actual funcionando y ya no se ejecutaria en segundo plano
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        //esto evita que se finalize el programa cuando cierrren esta ventana de registro de clientes
         setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
         
         
         
           
        //ponemos el fondo a la pantalla
         ImageIcon wallpaper= new ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\datasystem\\src\\main\\java\\imagenes\\wallpaperPrincipal.jpg");
        //ACA LE DECIMOS QUE jLabel_walpaper ESE NOMBRE DE VARIABLE QUE FUE LA QUE PUSIMOS EN EL FORMULARIO AL LABEL PARA EL FONO QUE COJA EL LARGO Y ANCHO Y LO ACOPLE A ESTA IMAGEN O QUE LA IMAGEN SE ACOMODE A ESAS MEDIDAS QUE NO SE VEA MAS GRANDE O AMS FEA SINO ACOMODADA
        Icon icono= new ImageIcon(wallpaper.getImage().getScaledInstance(fondoinformacioncliente.getWidth(),fondoinformacioncliente.getHeight(),Image.SCALE_DEFAULT));
       //AHORA LE DECIMOS QUE A ESE LABEL LE PONGA LA CONFIGURACION QUE HICIMOS EN LA LINEA ANTERIOR
        fondoinformacioncliente.setIcon(icono);
        //esta se pone para que aplique los cambios
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableinfoclientess = new javax.swing.JTable();
        infoclientemail = new javax.swing.JTextField();
        infoclientenombres = new javax.swing.JTextField();
        infoclientedireccion = new javax.swing.JTextField();
        infoclientetelefono = new javax.swing.JTextField();
        infoclientemodificadopor = new javax.swing.JTextField();
        btnActualizarcliente = new javax.swing.JButton();
        btnregistrarequipo1 = new javax.swing.JButton();
        btnimprimirclientex = new javax.swing.JButton();
        fondoinformacioncliente = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefono");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 130, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Direccion");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 160, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Ultima modificacion por:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 170, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Informacion del cliente");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 380, 50));

        tableinfoclientess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableinfoclientess);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 410, 190));
        getContentPane().add(infoclientemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 150, -1));
        getContentPane().add(infoclientenombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 150, -1));
        getContentPane().add(infoclientedireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 150, -1));
        getContentPane().add(infoclientetelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 150, -1));

        infoclientemodificadopor.setEditable(false);
        getContentPane().add(infoclientemodificadopor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 150, -1));

        btnActualizarcliente.setText("Actualizar cliente");
        btnActualizarcliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnActualizarcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 130, 30));

        btnregistrarequipo1.setText("Registar equipo");
        btnregistrarequipo1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnregistrarequipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 130, 30));

        btnimprimirclientex.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\datasystem\\src\\main\\java\\imagenes\\impresora.png")); // NOI18N
        getContentPane().add(btnimprimirclientex, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 90, 80));
        getContentPane().add(fondoinformacioncliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 389));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarcliente;
    private javax.swing.JButton btnimprimirclientex;
    private javax.swing.JButton btnregistrarequipo1;
    private javax.swing.JLabel fondoinformacioncliente;
    private javax.swing.JTextField infoclientedireccion;
    private javax.swing.JTextField infoclientemail;
    private javax.swing.JTextField infoclientemodificadopor;
    private javax.swing.JTextField infoclientenombres;
    private javax.swing.JTextField infoclientetelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableinfoclientess;
    // End of variables declaration//GEN-END:variables
}
