/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
//importamos la variable de sesion que viene por login
import static ventanas.Login.user;
 //importamos el nombre del usuario logueado que es quien va a registarar este cliente y viene desde la vista capturista
import static ventanas.Capturista.nombre_usuario_logueado;
/**
 *
 * @author Lenovo
 */
public class RegistarClientes extends javax.swing.JFrame {
    //la variable estatica de sesion que viene desde login 
    String user_logueado;
    //esta es para meter la variable del nombre del suario que esta logueado para colocarlo al crear el cliente como el creador
    String nombre_user_logueado;

    /**
     * Creates new form RegistarClientes
     */
    public RegistarClientes() {
        initComponents();
         //esta es para meter la variable del nombre del suario que esta logueado para colocarlo al crear el cliente como el creador
         nombre_user_logueado= Capturista.nombre_usuario_logueado;
        
         //TAMANP DE PANTALLA
         setSize(674, 351);
        //NO PUEDA CAMBIARLAS
        setResizable(false);
         //titulo de la intefaz de login
        setTitle("Panel capturista user logueado: "+user_logueado);
        //centrar la interface en la pantalla
        setLocationRelativeTo(null);
           //TAMANP DE PANTALLA
        
        //titulo de la intefaz de login
        setTitle("Panel Adminitrador sesion de -"+user);
       
         //matamos proceso cuando se loguean destruimos la ejecucion de login para que solo siga esta ventana actual funcionando y ya no se ejecutaria en segundo plano
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        //esto evita que se finalize el programa cuando cierrren esta ventana de registro de clientes
         setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
         //asignamos la variable de sesion a la estatica que venia de login
         user_logueado=Login.user;
       
       
        //ponemos el fondo a la pantalla
         ImageIcon wallpaper= new ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\datasystem\\src\\main\\java\\imagenes\\wallpaperPrincipal.jpg");
        //ACA LE DECIMOS QUE jLabel_walpaper ESE NOMBRE DE VARIABLE QUE FUE LA QUE PUSIMOS EN EL FORMULARIO AL LABEL PARA EL FONO QUE COJA EL LARGO Y ANCHO Y LO ACOPLE A ESTA IMAGEN O QUE LA IMAGEN SE ACOMODE A ESAS MEDIDAS QUE NO SE VEA MAS GRANDE O AMS FEA SINO ACOMODADA
        Icon icono= new ImageIcon(wallpaper.getImage().getScaledInstance(fondoregistarclientes.getWidth(),fondoregistarclientes.getHeight(),Image.SCALE_DEFAULT));
       //AHORA LE DECIMOS QUE A ESE LABEL LE PONGA LA CONFIGURACION QUE HICIMOS EN LA LINEA ANTERIOR
        fondoregistarclientes.setIcon(icono);
        //esta se pone para que aplique los cambios
        this.repaint();
        
        
      
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        emailcliente = new javax.swing.JTextField();
        telefonocliente = new javax.swing.JTextField();
        direccioncliente = new javax.swing.JTextField();
        nombrecliente3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btncrearcliente = new javax.swing.JButton();
        fondoregistarclientes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de clientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 360, 40));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefono:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 80, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Direccion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 80, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 80, -1));

        emailcliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(emailcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 240, -1));

        telefonocliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(telefonocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 240, -1));

        direccioncliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(direccioncliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 240, -1));

        nombrecliente3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(nombrecliente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 240, -1));

        jLabel6.setText("Desarrollado por: Camilo Agudelo ©");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 240, 20));

        btncrearcliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\datasystem\\src\\main\\java\\imagenes\\add.png")); // NOI18N
        btncrearcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearclienteActionPerformed(evt);
            }
        });
        getContentPane().add(btncrearcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 120, 100));
        getContentPane().add(fondoregistarclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 680, 351));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncrearclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearclienteActionPerformed
        // TODO add your handling code here:
         //matamos proceso cuando se loguean destruimos la ejecucion de login para que solo siga esta ventana actual funcionando y ya no se ejecutaria en segundo plano
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        //evitamos que al cerar este modal que no es el sistema pricipal evitamos que se nos cierre el sistema
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        int error=0;
        String nombre_cliente,email_cliente,telefono_cliente,direccion_cliente;
        //obtenemos los datos del formulario
        nombre_cliente=nombrecliente3.getText().trim();
        email_cliente=emailcliente.getText().trim();
        telefono_cliente=telefonocliente.getText().trim();
        direccion_cliente=direccioncliente.getText().trim();
        //validamos que no esten vacios losc ampos
        if(nombre_cliente.equals("")){
            nombrecliente3.setBackground(Color.red);
            error=error+1;
        }
        
           if(email_cliente.equals("")){
            emailcliente.setBackground(Color.red);
            error=error+1;
        }
           
        if(telefono_cliente.equals("")){
            telefonocliente.setBackground(Color.red);
            error=error+1;
        }
              
        if(direccion_cliente.equals("")){
            direccioncliente.setBackground(Color.red);
            error=error+1;
        }
        //si no hay errores procedemos a hacer la insercion de los registros en l db
        if(error==0){
          
                try{
                                                                   //creamos el objeto de conexion cada que creamos una nueva conexion y cerramos otra se debe cambiar la variable cn eneste caso pusimos cn2 al igual que el pst le pusimos pst2
                                                                   Connection cn=Conexion.conectar();
                                                                   // validamos si existe el usuario que trata de loguearse
                                                                   PreparedStatement pst2 = cn.prepareStatement("INSERT INTO clientes (nombre_cliente, email_cliente, tel_cliente, dir_cliente, ultima_modificacion) values(?,?,?,?,?)");
                                                                    pst2.setString(1, nombre_cliente);
                                                                    pst2.setString(2, email_cliente);
                                                                    pst2.setString(3, telefono_cliente);
                                                                    pst2.setString(4, direccion_cliente);
                                                                    pst2.setString(5, user_logueado);
                                                                    
                                                                    //ejecutamos el query
                                                                    pst2.executeUpdate();

                                                                    //cerramos la conexion
                                                                    cn.close();
                                                                    //llamamos al metodo que creamos de limpiar campos para que pinte un backrong verde y limpie campos
                                                                    limpiarCampos();
                                                                   
                                                                    
                                                                    JOptionPane.showMessageDialog(rootPane,"cliente creado satisfactoriamente");
                                                                    //le decimos que esta interface la cierre para reducisir recursos del pc
                                                                    this.dispose();
                                                        }catch(SQLException e){
                                                               System.err.println("Error todos los campos estan bien para agregar cliente panel RegistarClientes "+e);
                                                               JOptionPane.showMessageDialog(rootPane,"error al crear cliente ");
                                                        }

            
            
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "debes diligenciar todos los campos");
        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btncrearclienteActionPerformed

    //creamos la funcion para limpiar campos cuando ya todo esta listo
    public void limpiarCampos(){
        //limpiamos los campos y le ponemos un background verde
        nombrecliente3.setText("");
        nombrecliente3.setBackground(Color.green);
        emailcliente.setText("");
        emailcliente.setBackground(Color.green);
        telefonocliente.setText("");
        telefonocliente.setBackground(Color.green);
        direccioncliente.setText("");
        direccioncliente.setBackground(Color.green);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncrearcliente;
    private javax.swing.JTextField direccioncliente;
    private javax.swing.JTextField emailcliente;
    private javax.swing.JLabel fondoregistarclientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nombrecliente3;
    private javax.swing.JTextField telefonocliente;
    // End of variables declaration//GEN-END:variables
}
